projects:
  awesomenote:
    schemaPath: amplify/backend/api/awesomenote/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: awesomeAPI.swift
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
